// GENERATED by scripts/build-daily-verses.mjs. Do not edit by hand.
// Every quote is taken verbatim from the Swami Sivananda translation in the
// foundation's own dataset (github.com/gita/gita), so nothing here is written
// from memory. Re-run the script to change the selection.

export type DailyVerse = { quote: string; source: string };

export const TRANSLATOR = "Swami Sivananda";

export const DAILY_VERSES: DailyVerse[] = [
  {
    "quote": "Your right is only to work, but not to its results; do not let the results of action be your motive, nor let your attachment be to inaction.",
    "source": "Bhagavad Gita 2.47"
  },
  {
    "quote": "Perform action, O Arjuna, being steadfast in Yoga, abandoning attachment and balanced in success and failure; evenness of mind is called Yoga.",
    "source": "Bhagavad Gita 2.48"
  },
  {
    "quote": "Endowed with wisdom and evenness of mind, one casts off in this life both good and evil deeds; therefore, devote yourself to Yoga; Yoga is skill in action.",
    "source": "Bhagavad Gita 2.50"
  },
  {
    "quote": "He whose mind is not shaken by adversity, who does not long for pleasures, and is free from attachment, fear, and anger, is called a sage of steady wisdom.",
    "source": "Bhagavad Gita 2.56"
  },
  {
    "quote": "When one thinks of objects, attachment to them arises; from attachment, desire is born; from desire, anger arises.",
    "source": "Bhagavad Gita 2.62"
  },
  {
    "quote": "He attains peace into whom all desires enter, just as waters enter the ocean which, filled from all sides, remains unmoved; but not the man who is full of desires.",
    "source": "Bhagavad Gita 2.70"
  },
  {
    "quote": "That person attains peace who, abandoning all desires, moves about without longing, without the sense of ownership, and without egoism.",
    "source": "Bhagavad Gita 2.71"
  },
  {
    "quote": "Therefore, without attachment, always perform the actions that should be done; for by performing actions without attachment, one reaches the Supreme.",
    "source": "Bhagavad Gita 3.19"
  },
  {
    "quote": "Renouncing all actions in Me, with the mind centered on the Self, free from hope and egoism, and from mental fever, fight thou.",
    "source": "Bhagavad Gita 3.30"
  },
  {
    "quote": "Better is one's own duty, though devoid of merit, than the duty of another well discharged. Better is death in one's own duty; the duty of another is fraught with fear.",
    "source": "Bhagavad Gita 3.35"
  },
  {
    "quote": "Whenever there is a decline of righteousness and an increase of unrighteousness, O Arjuna, then I manifest Myself.",
    "source": "Bhagavad Gita 4.7"
  },
  {
    "quote": "For the protection of the good, for the destruction of the wicked, and for the establishment of righteousness, I am born in every age.",
    "source": "Bhagavad Gita 4.8"
  },
  {
    "quote": "In whatever way men approach Me, even so do I reward them; My path do men tread in all ways, O Arjuna.",
    "source": "Bhagavad Gita 4.11"
  },
  {
    "quote": "He who sees inaction in action and action in inaction, he is wise among men; he is a yogi and performer of all actions.",
    "source": "Bhagavad Gita 4.18"
  },
  {
    "quote": "Brahman is the oblation; Brahman is the melted butter (ghee); by Brahman is the oblation poured into the fire of Brahman; Brahman indeed shall be attained by one who always sees Brahman in action.",
    "source": "Bhagavad Gita 4.24"
  },
  {
    "quote": "Verily, there is no purifier in this world like knowledge. He who is perfected in Yoga finds it within the Self in due time.",
    "source": "Bhagavad Gita 4.38"
  },
  {
    "quote": "The one who is full of faith, devoted to it, and has subdued their senses obtains this knowledge; and upon obtaining the knowledge, they attain the supreme peace immediately.",
    "source": "Bhagavad Gita 4.39"
  },
  {
    "quote": "He who does actions, offering them to Brahman and abandoning attachment, is not tainted by sin, just as a lotus leaf is not tainted by water.",
    "source": "Bhagavad Gita 5.10"
  },
  {
    "quote": "Sages look with an equal eye on a Brahmana endowed with learning and humility, on a cow, an elephant, a dog, and even an outcaste.",
    "source": "Bhagavad Gita 5.18"
  },
  {
    "quote": "With the self unattached to external contacts, he finds happiness in the Self; with the self engaged in the meditation of Brahman, he attains endless happiness.",
    "source": "Bhagavad Gita 5.21"
  },
  {
    "quote": "He who knows Me as the enjoyer of sacrifices and austerities, the great Lord of all the worlds, and the friend of all beings, attains peace.",
    "source": "Bhagavad Gita 5.29"
  },
  {
    "quote": "One should raise oneself by one's own self alone; let not one lower oneself; for the self alone is one's own friend, and the self alone is one's own enemy.",
    "source": "Bhagavad Gita 6.5"
  },
  {
    "quote": "As a lamp placed in a windless spot does not flicker, so is the Yogi of a controlled mind, who practices Yoga in the Self, compared.",
    "source": "Bhagavad Gita 6.19"
  },
  {
    "quote": "Having obtained it, he thinks there is no other gain superior to it; established in it, he is not moved even by heavy sorrow.",
    "source": "Bhagavad Gita 6.22"
  },
  {
    "quote": "From whatever cause the restless and unsteady mind wanders away, let him restrain it from that and bring it under the control of the Self alone.",
    "source": "Bhagavad Gita 6.26"
  },
  {
    "quote": "With the mind harmonized by Yoga, he sees the Self abiding in all beings and all beings in the Self; he sees the same everywhere.",
    "source": "Bhagavad Gita 6.29"
  },
  {
    "quote": "He who sees Me everywhere and sees everything in Me, never becomes separated from Me, nor do I from him.",
    "source": "Bhagavad Gita 6.30"
  },
  {
    "quote": "He who, through the likeness of the Self, O Arjuna, sees reality everywhere, be it pleasure or pain, is regarded as the highest Yogi.",
    "source": "Bhagavad Gita 6.32"
  },
  {
    "quote": "The Blessed Lord said, \"Undoubtedly, O mighty-armed Arjuna, the mind is difficult to control and restless; but with practice and dispassion, it can be restrained.\"",
    "source": "Bhagavad Gita 6.35"
  },
  {
    "quote": "There is nothing higher than Me, O Arjuna. All this is strung on Me, like clusters of gems on a string.",
    "source": "Bhagavad Gita 7.7"
  },
  {
    "quote": "I am the flavor in water, O Arjuna; I am the light in the moon and the sun; I am the syllable Om in all the Vedas, sound in the ether and virility in men.",
    "source": "Bhagavad Gita 7.8"
  },
  {
    "quote": "Verily, this divine illusion of Mine, composed of the three qualities, is difficult to cross over; those who take refuge in Me alone, can cross over this illusion.",
    "source": "Bhagavad Gita 7.14"
  },
  {
    "quote": "Four kinds of virtuous men worship Me, O Arjuna, and they are the distressed, the seekers of knowledge, the seekers of wealth, and the wise, O Lord of the Bharatas.",
    "source": "Bhagavad Gita 7.16"
  },
  {
    "quote": "Of them, the wise who are ever steadfast and devoted to the One, excel; for I am exceedingly dear to the wise, and they are dear to Me.",
    "source": "Bhagavad Gita 7.17"
  },
  {
    "quote": "At the end of many births, the wise man comes to Me, realizing that all this is Vaasudeva (the innermost Self); such a great soul (Mahatma) is very hard to find.",
    "source": "Bhagavad Gita 7.19"
  },
  {
    "quote": "I am not manifest to all, veiled as I am by the Yoga-Maya. This deluded world does not know Me, who am unborn and imperishable.",
    "source": "Bhagavad Gita 7.25"
  },
  {
    "quote": "And whoever, leaving their body, goes forth remembering Me alone at the time of death, they will attain My Being; there is no doubt about this.",
    "source": "Bhagavad Gita 8.5"
  },
  {
    "quote": "Therefore, at all times, remember Me only and fight. With your mind and intellect fixed on Me, you will undoubtedly come to Me alone.",
    "source": "Bhagavad Gita 8.7"
  },
  {
    "quote": "I am easily attainable by that ever-steadfast yogi who constantly and daily remembers me for a long time, not thinking of anything else with a single-minded or one-pointed focus, O Partha.",
    "source": "Bhagavad Gita 8.14"
  },
  {
    "quote": "Having attained Me, these great souls do not take birth again here, a place of pain and impermanence, but have reached the highest perfection of liberation.",
    "source": "Bhagavad Gita 8.15"
  },
  {
    "quote": "This is the royal science, the royal secret, the supreme purifier, realizable by direct intuitive knowledge, according to righteousness, very easy to perform and imperishable.",
    "source": "Bhagavad Gita 9.2"
  },
  {
    "quote": "But the great souls, O Arjuna, partaking of My divine nature, worship Me with a single-minded devotion, knowing Me as the imperishable source of all beings.",
    "source": "Bhagavad Gita 9.13"
  },
  {
    "quote": "Always glorifying Me, striving, firm in their vows, prostrating themselves before Me, they worship Me with steadfast devotion.",
    "source": "Bhagavad Gita 9.14"
  },
  {
    "quote": "I am the father of this world, the mother, the dispenser of the fruits of actions, and the grandfather; the one thing to be known, the purifier, the sacred monosyllable (Om), and also the Rik, Sama, and Yajur Vedas.",
    "source": "Bhagavad Gita 9.17"
  },
  {
    "quote": "For those men who worship Me alone, thinking of no one else, for those ever-united, I secure what they have not already possessed and preserve what they already possess.",
    "source": "Bhagavad Gita 9.22"
  },
  {
    "quote": "Whoever offers Me with devotion a leaf, a flower, a fruit, or a little water, that, so offered devotedly by the pure-minded, I accept.",
    "source": "Bhagavad Gita 9.26"
  },
  {
    "quote": "Whatever you do, whatever you eat, whatever you offer in sacrifice, whatever you give, whatever austerity you practice, O Arjuna, do it as an offering to Me.",
    "source": "Bhagavad Gita 9.27"
  },
  {
    "quote": "I am the same to all beings; there is none hateful or dear to Me; but those who worship Me with devotion are in Me, and I am also in them.",
    "source": "Bhagavad Gita 9.29"
  },
  {
    "quote": "Even if the most sinful worships Me, with devotion to no one else, he should indeed be regarded as righteous, for he has rightly resolved.",
    "source": "Bhagavad Gita 9.30"
  },
  {
    "quote": "Soon he becomes righteous and attains eternal peace; O Arjuna, proclaim thou for certain that My devotee never perishes.",
    "source": "Bhagavad Gita 9.31"
  },
  {
    "quote": "Fix your mind on Me; be devoted to Me; sacrifice to Me; bow down to Me; having thus united your whole self to Me, taking Me as the supreme goal, you will come to Me.",
    "source": "Bhagavad Gita 9.34"
  },
  {
    "quote": "I am the source of all; from me everything evolves; Understanding this, the wise, endowed with meditation, worship me.",
    "source": "Bhagavad Gita 10.8"
  },
  {
    "quote": "With their minds and lives wholly absorbed in Me, they enlighten each other and ever speak of Me, being satisfied and delighted.",
    "source": "Bhagavad Gita 10.9"
  },
  {
    "quote": "To those who are ever steadfast, worshipping me with love, I give the yoga of discrimination, by which they come to me.",
    "source": "Bhagavad Gita 10.10"
  },
  {
    "quote": "Out of mere compassion for them, I, dwelling within their selves, destroy the darkness born of ignorance with the luminous lamp of knowledge.",
    "source": "Bhagavad Gita 10.11"
  },
  {
    "quote": "I am the Self, O Gudakesa, seated in the hearts of all beings; I am the beginning, the middle, and the end of all beings.",
    "source": "Bhagavad Gita 10.20"
  },
  {
    "quote": "Whatever being there is glorious, prosperous, or powerful, know that to be a manifestation of a part of My splendor.",
    "source": "Bhagavad Gita 10.41"
  },
  {
    "quote": "Thou art the Father of this world, both moving and unmoving. Thou art to be adored by this world; Thou, the greatest Guru; for none exists who is equal to Thee; how then could there be another superior to Thee in the three worlds, O Being of unrivaled power?",
    "source": "Bhagavad Gita 11.43"
  },
  {
    "quote": "Therefore, bowing down and prostrating my body, I crave Thy forgiveness, O adorable Lord. As a father forgives his son, a friend his dear friend, a lover his beloved, even so may Thou forgive me, O God.",
    "source": "Bhagavad Gita 11.44"
  },
  {
    "quote": "But by single-minded devotion, I can be known, seen, and entered into in reality, O Arjuna.",
    "source": "Bhagavad Gita 11.54"
  },
  {
    "quote": "He who does all actions for Me, who regards Me as the Supreme, who is devoted to Me, who is free from attachment, who bears no enmity towards any creature, he comes to Me, O Arjuna.",
    "source": "Bhagavad Gita 11.55"
  },
  {
    "quote": "But to those who worship Me, renouncing all actions in Me, regarding Me as the supreme goal, meditating on Me with single-minded yoga.",
    "source": "Bhagavad Gita 12.6"
  },
  {
    "quote": "Fix your mind on Me, and your intellect in Me. Then you will certainly live in Me alone hereafter.",
    "source": "Bhagavad Gita 12.8"
  },
  {
    "quote": "He who hates no creature, is friendly and compassionate to all, is free from attachment and egoism, is balanced in pleasure and pain, and is forgiving.",
    "source": "Bhagavad Gita 12.13"
  },
  {
    "quote": "Ever content, steady in meditation, self-controlled, possessing firm conviction, with the mind and intellect dedicated to Me, he, My devotee, is dear to Me.",
    "source": "Bhagavad Gita 12.14"
  },
  {
    "quote": "He whom the world does not agitate, and who cannot be agitated by the world, and who is freed from joy, anger, fear, and anxiety, he is dear to Me.",
    "source": "Bhagavad Gita 12.15"
  },
  {
    "quote": "He who neither rejoices nor hates, nor grieves nor desires, renouncing both good and evil, and who is full of devotion, is dear to Me.",
    "source": "Bhagavad Gita 12.17"
  },
  {
    "quote": "They who follow this immortal Dharma, endowed with faith and regarding Me as their supreme goal, are exceedingly dear to Me.",
    "source": "Bhagavad Gita 12.20"
  },
  {
    "quote": "Wherever a being is born, whether unmoving or moving, know thou, O best of the Bharatas (Arjuna), that it is from the union of the field and its knower.",
    "source": "Bhagavad Gita 13.27"
  },
  {
    "quote": "He who sees the Supreme Lord existing truly in all beings, the imperishable within the perishable, sees indeed.",
    "source": "Bhagavad Gita 13.28"
  },
  {
    "quote": "And he who serves Me with unwavering devotion, he, crossing beyond the dualities, is fit for becoming Brahman.",
    "source": "Bhagavad Gita 14.26"
  },
  {
    "quote": "For I am the abode of Brahman, the immortal, immutable, and everlasting Dharma, and absolute bliss.",
    "source": "Bhagavad Gita 14.27"
  },
  {
    "quote": "Free from pride and delusion, victorious over the evil of attachment, dwelling constantly in the Self, their desires having completely turned away, freed from the pairs of opposites known as pleasure and pain, they, the undeluded, reach the eternal goal.",
    "source": "Bhagavad Gita 15.5"
  },
  {
    "quote": "Neither does the sun illuminate there, nor the moon, nor the fire; having gone there, they do not return; that is My supreme abode.",
    "source": "Bhagavad Gita 15.6"
  },
  {
    "quote": "And I am seated in the hearts of all; from Me come memory and knowledge, as well as their absence. I am verily That which has to be known by all the Vedas; I am indeed the author of the Vedanta and the knower of the Vedas.",
    "source": "Bhagavad Gita 15.15"
  },
  {
    "quote": "He who, undeluded, knows Me as the highest Purusha, he, knowing all, worships Me with his whole being (heart), O Arjuna.",
    "source": "Bhagavad Gita 15.19"
  },
  {
    "quote": "The Blessed Lord said: Fearlessness, purity of heart, steadfastness in knowledge and yoga, almsgiving, control of the senses, sacrifice, study of scriptures, austerity, and straightforwardness.",
    "source": "Bhagavad Gita 16.1"
  },
  {
    "quote": "Harmlessness, truth, absence of anger, renunciation, peacefulness, absence of crookedness, compassion for beings, non-covetousness, gentleness, modesty, and absence of fickleness.",
    "source": "Bhagavad Gita 16.2"
  },
  {
    "quote": "Vigor, forgiveness, fortitude, purity, absence of hatred, absence of pride, these belong to one born for a divine state, O Arjuna.",
    "source": "Bhagavad Gita 16.3"
  },
  {
    "quote": "The faith of each is in accordance with their nature, O Arjuna. People consist of their faith; as a person's faith is, so are they.",
    "source": "Bhagavad Gita 17.3"
  },
  {
    "quote": "He from whom all the beings have evolved and by whom all this is pervaded, worshipping Him with his own duty, one attains perfection.",
    "source": "Bhagavad Gita 18.46"
  },
  {
    "quote": "Becoming Brahman, serene in the Self, he neither grieves nor desires; he is the same to all beings, and obtains supreme devotion to Me.",
    "source": "Bhagavad Gita 18.54"
  },
  {
    "quote": "By devotion, he knows Me in truth, who and what I am; then, having known Me in truth, he immediately enters into the Supreme.",
    "source": "Bhagavad Gita 18.55"
  },
  {
    "quote": "The Lord dwells in the hearts of all beings, O Arjuna, causing all beings, by His illusory power, to revolve as if mounted on a machine.",
    "source": "Bhagavad Gita 18.61"
  },
  {
    "quote": "Fly to Him for refuge with all your being, O Arjuna; by His grace you will obtain supreme peace and the eternal abode.",
    "source": "Bhagavad Gita 18.62"
  },
  {
    "quote": "Fix your mind on Me, be devoted to Me, sacrifice to Me, bow down to Me. You will come to Me; I truly promise you this, for you are dear to Me.",
    "source": "Bhagavad Gita 18.65"
  },
  {
    "quote": "Abandon all duties and take refuge in Me alone; I will liberate you from all sins; do not grieve.",
    "source": "Bhagavad Gita 18.66"
  },
  {
    "quote": "Wherever Krishna, the Lord of Yoga, is; and wherever Arjuna, the wielder of the bow, is; there is prosperity, victory, happiness, and a firm policy; this is my conviction.",
    "source": "Bhagavad Gita 18.78"
  }
];
